#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2020             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#example output
#<<<hitachivsp_clprs:sep(9)>>>
#clprId  cacheMemoryCapacity     cacheMemoryUsedCapacity writePendingDataCapacity        cacheUsageRate
#0       924672  901454  44959   99


def inventory_hitachivsp_clprs(info):
    for line in info:
        if "clprId" not in line:
            yield line[0], {}


def check_hitachivsp_clprs(item, params, info):
    for line in info:
        if item == line[0]:
           yield 0, "CacheMemoryCapacity[GB]: %s ; CacheMemoryUsedCapacity[GB]: %s ; cacheUsageRate %s " % \
                 ( int(line[1])/1024 , int(line[2])/1024, line[4] ), \
                 [("CacheMemoryCapacity", int(line[1])/1024, None, None, 0),
                  ("CacheMemoryUsedCapacity", int(line[2])/1024, None, None, 0),
                  ("CacheUsageRate", line[4], None, None, 0)]


check_info['hitachivsp_clprs'] = {
    'inventory_function': inventory_hitachivsp_clprs,
    'check_function': check_hitachivsp_clprs,
    'service_description': 'CLPR %s',
    'has_perfdata': True
}
