#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2020             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#example output
#<<<hitachivsp_drive_boxes_dbps:sep(9)>>>
#drivebox_location	dbps_location	dbps_status
#DB-00	DBPS00-1	Normal
#DB-00	DBPS00-2	Normal
#DB-01	DBPS01-1	Normal
#DB-01	DBPS01-2	Normal
#DB-02	DBPS02-1	Normal
#DB-02	DBPS02-2	Normal
#DB-03	DBPS03-1	Normal
#DB-03	DBPS03-2	Normal

def inventory_hitachivsp_drive_boxes_dbps(info):
    for line in info:
        if "dbps_location" not in line:
            yield line[1], {}


def check_hitachivsp_drive_boxes_dbps(item, params, info):
    for line in info:
        if "dbps_location" not in line:
            if item == line[1]:
                if line[2] == "Normal":
                    yield 0, "DriveBox Power Supply status is Normal"
                elif line[2] == "Warning":
                    yield 1, "DriveBox Power Supply status is Warning"
                elif line[2] == "Failed":
                    yield 2, "DriveBox Power Supply status is Failed"


check_info['hitachivsp_drive_boxes_dbps'] = {
    'inventory_function': inventory_hitachivsp_drive_boxes_dbps,
    'check_function': check_hitachivsp_drive_boxes_dbps,
    'service_description': 'DriveBox Power supply %s',
    'has_perfdata': False
}

