#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2020             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#example output
#<<<hitachivsp_channel_board:sep(9)>>>
#location	status	type
#CHB-1A	Normal	32G Ready 4Port FC
#CHB-1B	Normal	32G Ready 4Port FC
#CHB-2A	Normal	32G Ready 4Port FC
#CHB-2B	Normal	32G Ready 4Port FC


def inventory_hitachivsp_cache_flash_memories(info):
    for line in info:
        if "location" not in line:
            yield line[0], {}


def check_hitachivsp_cache_flash_memories(item, params, info):
    for line in info:
        if item == line[0]:
            if line[1] == "Normal":
                yield 0, "Cache memory status is Normal"
            elif line[1] == "Warning":
                yield 1, "Cache memory status is Warning"
            elif line[1] == "Blocked":
                yield 2, "Cache memory status is Blocked"
            elif line[1] == "Failed":
                yield 2, "Cache memory status is Failed"


check_info['hitachivsp_cache_flash_memories'] = {
    'inventory_function': inventory_hitachivsp_cache_flash_memories,
    'check_function': check_hitachivsp_cache_flash_memories,
    'service_description': 'Cache Flash Memory %s',
    'has_perfdata': True
}

