#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#<<<vcenter_srm>>>
#LocalConnection com.vmware.cis.vcenterserver	https://buc01m01vc01.test:443/sdk	Connected
#LocalConnection com.vmware.cis.cs.inventory	https://buc01m01vc01.test:443/invsvc/vmomi/sdk	Connected
#LocalConnection com.vmware.cis.cs.lookup	https://buc01psc01.test:443/lookupservice/sdk	Connected
#LocalConnection com.vmware.cis.cs.identity	https://buc01psc01.test/sso-adminserver/sdk/vsphere.local	Connected
#LocalConnection com.vmware.cis.cs.authorization	https://buc01m01vc01.test:443/invsvc/vmomi/sdk	Connected
#LocalConnection com.vmware.cis.cs.license	https://buc01psc01.test:443/ls/sdk	Connected
#RemoteConnection com.vmware.cis.vcenterserver	https://buc01m01vc01.test:443/sdk	Connected
#RemoteConnection com.vmware.dr.vcDr	https://buc01m01vc01.test:443/invsvc/vmomi/sdk	Connected
#RemoteConnection com.vmware.cis.cs.lookup	https://buc01psc01.test:443/lookupservice/sdk	Connected
#RemoteConnection com.vmware.cis.cs.identity	https://buc01psc01.test/sso-adminserver/sdk/vsphere.locaConnected

import datetime

def inventory_srm_status(info):
    for servicename, url, state in info:
	yield ("%s" % (servicename), {})


def check_srm_status(item, params, info):
    for line in info:
        if line[0]==item:
           if line[2]=="Connected":
               return 0, "OK, %s is %s; %s" % (item,line[2],line[1])
	   else:
	       return 1, "CRIT, %s is %s; %s" % (item,line[2],line[1])

check_info['vcenter_srm'] = {
    'inventory_function'    : inventory_srm_status,
    'check_function'        : check_srm_status,
    'service_description'   : '%s', 
    'has_perfdata'          : False,
}
