#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


# example output



def inventory_broadworks_ms_port_errors(info):
    return [ (None, {}) ]

def check_broadworks_ms_port_errors(item, params, info):
    if int(info[0][0]) == 0:
	state = 0
	infotext = "OK - No Errors"
        perf = [("Erori", int(info[0][0]) )]
        return (state, infotext, perf)
    else:
	state = 1
        infotext = "WARN - Errors are present: %s errors" % int(info[0][0])
        perf = [("Erori", int(info[0][0]) )]
        return (state, infotext, perf)


check_info['broadworks_ms_port_errors'] = {
    'inventory_function'    : inventory_broadworks_ms_port_errors,
    'check_function'        : check_broadworks_ms_port_errors,
    'service_description'   : 'msNoPortAvailableErrors',
    'snmp_info'             : ('.1.3.6.1.4.1.6431.1.3.1.6', [ "0",]),
    'has_perfdata'          : True,
    'snmp_scan_function'    : lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.6431"),
}
